### ISSUE TITLE
请问这一步是什么意思？

### ISSUE THREAD

**Issue by hnty545** [eggjs/egg-rpc-for-apache-dubbo#11]
请问这一步是什么意思？
First, you need to put the JAR file (which contains the API interfaces) into {app_root}/assembly folder.

**Comment by hnty545** [comment]
npm run rpc
没有生成任何proxy

**Comment by hnty545** [comment]
"egg-rpc-for-apache-dubbo": "^1.0.0"
"egg-rpc-generator": "^1.3.1"

**Comment by hnty545** [comment]
现在npm run rpc之后只生成了proxy-class，没有生成proxy的接口文件，请问可能是什么问题呢

**Comment by cnlinge** [comment]
> npm run rpc
> 没有生成任何proxy

需要书写proto接口描述文件
https://www.npmjs.com/package/egg-rpc-generator

**Comment by hnty545** [comment]
@cnlinge 你好
我用的是jar2proxy的方式

**Comment by cnlinge** [comment]
![image](https://user-images.githubusercontent.com/17809360/63337400-81eda000-c373-11e9-87be-9cdba218ba41.png)
坑太多了，最后我用的 node-zookeeper-dubbo ，这个很好

**Comment by hnty545** [comment]
@cnlinge 请问怎么在egg里使用呢，要自己封装插件吗

**Comment by cnlinge** [comment]
不需要
"use strict";
const nzd = require("node-zookeeper-dubbo");
const java = require("js-to-java");
const opt = {
  application: { name: "xxx" },
  registry: "192.168.x.xx:2181",
  dubboVer: "2.10.0x",
  root: "dubbo",
  dependencies: {
    SupplierStatementService: {
      interface: "com.sprucetec.xxx.service.provide.xxxxxx",
      version: "base",
      timeout: 10000,
      group: "xxxxx",
      methodSignature: {
        selectCurMonStatements: id => [{ $class: "java.lang.Long", $: id }]
      }
    }
  }
};
const dubboBaseService = new nzd(opt);
dubboBaseService.on("service:changed", event => console.log(event));
module.exports = dubboBaseService;

**Comment by cnlinge** [comment]
`"use strict";
const nzd = require("node-zookeeper-dubbo");
const java = require("js-to-java");
const opt = {
  application: { name: "xxx" },
  registry: "192.168.x.xx:2181",
  dubboVer: "2.10.0x",
  root: "dubbo",
  dependencies: {
    SupplierStatementService: {
      interface: "com.sprucetec.xxx.service.provide.xxxxxx",
      version: "base",
      timeout: 10000,
      group: "xxxxx",
      methodSignature: {
        selectCurMonStatements: id => [{ $class: "java.lang.Long", $: id }]
      }
    }
  }
};
const dubboBaseService = new nzd(opt);
dubboBaseService.on("service:changed", event => console.log(event));
module.exports = dubboBaseService;
`

**Comment by cnlinge** [comment]
```
"use strict";
const nzd = require("node-zookeeper-dubbo");
const java = require("js-to-java");
const opt = {
  application: { name: "xxx" },
  registry: "192.168.x.xx:2181",
  dubboVer: "2.10.0x",
  root: "dubbo",
  dependencies: {
    SupplierStatementService: {
      interface: "com.sprucetec.xxx.service.provide.xxxxxx",
      version: "base",
      timeout: 10000,
      group: "xxxxx",
      methodSignature: {
        selectCurMonStatements: id => [{ $class: "java.lang.Long", $: id }]
      }
    }
  }
};
const dubboBaseService = new nzd(opt);
dubboBaseService.on("service:changed", event => console.log(event));
module.exports = dubboBaseService;

```

**Comment by cnlinge** [comment]
不用封装插件，写一个sevice就可以了

**Comment by hnty545** [comment]
Daniel1989/egg-dubbo
他好像是封装了一个

**Comment by cnlinge** [comment]
egg-dubbo 这一套相关的东西太多了 太杂，坑太多 整了好久都不行。最后困在两个问题上
The socket was closed. (address: address => bolt://192.168.2.26:2181)
No provider of com.sprucetec.pms.srm.api.supplierRelativeApi:1.0@SOFA:getSupplierByIds() found!
放弃了！

**Comment by hnty545** [comment]
这个怎么调用呢

**Comment by hnty545** [comment]
我现在在用Daniel1989/egg-dubbo
但是不知道怎么调用，也没有例子

**Comment by hnty545** [comment]
我明白了，是egg的config里的配置

**Comment by hnty545** [comment]
你用Daniel1989/egg-dubbo怎么调用的，方便给个例子吗？谢谢！

我是这样调用
return this.ctx.dubbo(
        'MemberManageFacade',
        'getMemberByAccessToken',
        {
          token,
          userId,
          brandCardPart,
          termId
        }
      );
----------------
exports.dubboclient = {
    dubboAgent: {
      application: { name: 'dubbo-consumer' },
      register: '10.200.201.67:2181',
      dubboVer: '2.5.3',
      root: 'dubbo',
      dependencies: {
        MemberManageFacade: {
          interface:
            'cn.xxx.member.common.service.facade.MemberManageFacade'
        }
      }
    }
  };
------------
但是报错
TypeError: Cannot read property 'charAt' of undefined
    at Encode._argsType (C:\_develop\workspace_node\node-bff\node_modules\node-zookeeper-dubbo\libs\encode.js:65:14)
    at Encode._body (C:\_develop\workspace_node\node-bff\node_modules\node-zookeeper-dubbo\libs\encode.js:39:19)
    at new Encode (C:\_develop\workspace_node\node-bff\node_modules\node-zookeeper-dubbo\libs\encode.js:10:21)
    at Service._execute (C:\_develop\workspace_node\node-bff\node_modules\node-zookeeper-dubbo\index.js:141:31)
    at Service.getMemberByAccessToken (C:\_develop\workspace_node\node-bff\node_modules\node-zookeeper-dubbo\index.js:115:27)
    at DubboClient.request (C:\_develop\workspace_node\node-bff\node_modules\egg-dubbo-plugin\app.js:14:55)
    at Object.dubbo (C:\_develop\workspace_node\node-bff\node_modules\egg-dubbo-plugin\app\extend\context.js:10:29)
    at UserConnector.getUserInfo (C:\_develop\workspace_node\node-bff\app\graphql\user\connector.js:17:23)
    at userInfo (C:\_develop\workspace_node\node-bff\app\graphql\user\resolver.js:25:33)
    at field.resolve (C:\_develop\workspace_node\node-bff\node_modules\graphql-extensions\dist\index.js:133:26)
